"""
Django settings for alu project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import json
import os

import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEBUG = env.bool('ALU_DEBUG')
PRODUCTION = env.bool('ALU_PRODUCTION')

ADMINS = env.json('ADMINS')

ALLOWED_CHARS = 'bcdfghjkmpqrtvwxyBCDFGHJKMPQRTVWXY346789-_'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = [
    'www.alulearn.com',
    'alulearn.com',
    'useruploads.alulearn.com',
    'www.useruploads.alulearn.com',
    '127.0.0.1',
    'localhost',
    'dev.alulearn.com',
]
CORS_ORIGIN_WHITELIST = [
    'https://alulearn.com',
    'https://www.alulearn.com',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://dev.alulearn.com:3000',
    'http://dev.alulearn.com:8000',
    'http://localhost',
]

DOMAIN_URL = 'http://127.0.0.1:8000' if DEBUG else 'https://alulearn.com'

INTERNAL_IPS = ['127.0.0.1']


# Application definition

CORE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INTERNAL_APPS = [
    'decks',
    'accounts',
    'profiles',
    'analytics',
    'pages',
    'teachers',
    'habits',
    'skill_tree',
    'sharing_system',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'corsheaders',
    'django_user_agents',
    'debug_toolbar',
    'user_visit',
    'storages',
    'django_inlinecss',
    'django_gsuite_email',
]

INSTALLED_APPS = CORE_APPS + INTERNAL_APPS + THIRD_PARTY_APPS

CELERY_BROKER_URL = 'redis://localhost:6379'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'user_visit.middleware.UserVisitMiddleware',
]

# Start with `memcached -p 11211`
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'OPTIONS': {
            # Object size limit = 2MB
            'server_max_value_length': 1024 * 1024 * 2,
        },
    }
}

ROOT_URLCONF = 'alu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# Change password: ALTER USER user WITH PASSWORD 'password';
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'alu',
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

# Email Configuration
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_PORT = 587
EMAIL_BACKEND = (
    'django.core.mail.backends.filebased.EmailBackend'
    if DEBUG else
    'django_gsuite_email.GSuiteEmailBackend'
)
GSUITE_CREDENTIALS_FILE = env('GSUITE_CREDENTIALS_FILE')
EMAIL_FILE_PATH = '/tmp/alu-debug-emails/'  # in DEBUG, save emails to the filesystem

DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')
SERVER_EMAIL = env('EMAIL_HOST_USER')

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
if not DEBUG:
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = 'alu-user-uploads'
    AWS_S3_ENDPOINT_URL = 'https://nyc3.digitaloceanspaces.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = ''  # uploaded to the "uploads" folder in the DO Space

    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
else:
    # Uploaded files and media
    UPLOADED_FILES_FILEPATH = os.path.join(BASE_DIR, 'uploads/')
    UPLOADED_FILES_URLPATH = '/uploads/'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static-root')

# Other
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DEFAULT_AUTHENTICATION_CLASSES = [
    'rest_framework.authentication.SessionAuthentication',
]

DEFAULT_RENDERER_CLASSES = [
    'rest_framework.renderers.JSONRenderer',
]

if DEBUG:
    DEFAULT_RENDERER_CLASSES += ['rest_framework.renderers.BrowsableAPIRenderer']
    DEFAULT_AUTHENTICATION_CLASSES += ['alu.rest_api.dev.DevAuthentication']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': DEFAULT_AUTHENTICATION_CLASSES,
    'DEFAULT_RENDERER_CLASSES': DEFAULT_RENDERER_CLASSES,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'alu.throttling.ExceptionalUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'OVERRIDE_THROTTLE_RATES': {
        'evolvedsquid': '10000/hour',
    },
}

# Other
INLINECSS_CSS_LOADER = 'django_inlinecss.css_loaders.StaticfilesFinderCSSLoader'


# Backups
DB_BACKUP_DIR = os.path.join(BASE_DIR, 'backups/')

# User agent context
CHROME_USER_AGENT = (
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
    'Chrome/94.0.4606.61 Safari/537.36'
)
ALU_USER_AGENT = (
    f'AluLearn.com Image Proxy (Alu is a free education site; {DOMAIN_URL}/legal/imageproxy/ )'
)
USER_AGENT_HEADERS = {
    'User-Agent': CHROME_USER_AGENT if DEBUG else ALU_USER_AGENT,
    'From': None if DEBUG else EMAIL_HOST_USER,
}

# Explore decks
with open('editor_deck_ids.json', 'r') as f:
    EDITOR_PICKS_DECK_IDS = json.loads(f.read())

# Payments
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_ENDPOINT_SECRET = env('STRIPE_ENDPOINT_SECRET')
STRIPE_MONTHLY_PRO_ID = env('STRIPE_MONTHLY_PRO_ID')
STRIPE_YEARLY_PRO_ID = env('STRIPE_YEARLY_PRO_ID')

PRO_MODE_PARTNERS = env.json('PRO_MODE_PARTNERS')
FREE_TRIAL_LENGTH = env.int('FREE_TRIAL_LENGTH')

# Slack
ALU_BOT_APP_TOKEN = env('ALU_BOT_APP_TOKEN')
ALU_BOT_OATH_TOKEN = env('ALU_BOT_OATH_TOKEN')
ALU_BOT_SIGNING_SECRET = env('ALU_BOT_SIGNING_SECRET')
SLACK_NOTIFICATION_CHANNEL = env('SLACK_NOTIFICATION_CHANNEL')

# Google OAuth
GOOGLE_OAUTH2_CLIENT_ID = env('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = env('GOOGLE_OAUTH2_CLIENT_SECRET')
