const randomTips = [
  // Actual relevant tips
  'Use "Tab" to cycle through fields when creating flashcards',
  'You can choose to share decks with friends only',
  'Friends make Alu even better!',
  'Enjoying Alu? Don\'t forget to tell your friends!',
  'Looking for a pre-made deck? Check out the "explore" tab.',
  'Looking for a specific pre-made deck? Use the "search" tab.',
  'Alu automatically recognizes cards you have trouble learning, and tags them as "leeches".',
  'You can add a bio and location to tell others more about yourself.',
  'You can give each deck a custom description.',
  'Is 20 new cards per day too much? Too little? You can change this value in the deck\'s settings.',
  'Looking to study in advance? Change the "review ahead" or "increase new cards limit" in custom study.',
  'Deleted decks can never be recovered! Be careful!',
  'Tooltips annoying you? Disable them by enabling "expert mode" in settings.',
  'Alu estimates how easy or hard a card is using an "ease factor". This determines when you next see the card.',
  'Suspended cards are never shown to you when studying. Use this feature to temporarily disable cards.',
  'Give flashcards tags to organize them',
  'Want to study a specific set of cards? Use the "Custom Study" feature.',
  'When studying flashcards, use the spacebar to reveal the answer and the number keys (1-4) to select a choice',
  'You can share decks with others by changing the "Sharing Setting" value',
  'When creating cards, click the snowflake icon to "freeze" a field',
  'You can write MarkDown, LaTeX, and HTML when creating flashcards and deck descriptions',
  'You can import flashcards from other popular flashcard programs using the "import" feature',
  'When taking notes, we recommend you disable spell checking, and focus more on the content than spelling and grammar',
  'Turning off notifications when taking notes or attending class can help you focus and create better notes',
  'Use the "Flashcard Search" feature to find flashcards',
  'You can create a "filtered deck" out of flashcards with the "Flashcard Search" feature. This is useful if you are trying to study a specific topic you need extra help on.',
  // Random stuff
  '42 (forty-two) is the natural number that follows 41 and precedes 43.',
  'Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.',
  'Some static you see on TV screens is residual radiation from the big-bang.',
];

export const randomTip = randomTips[Math.floor(Math.random()*randomTips.length)];