const randomTips = [
  // Actual relevant tips
  'Use "Tab" to cycle through fields when creating flashcards',
  'You can choose to share decks with friends only',
  'Friends make Alu even better!',
  'Enjoying Alu? Don\'t forget to tell your friends!',
  'Looking for a pre-made deck? Check out the "explore" tab.',
  'Looking for a specific pre-made deck? Use the "search" tab.',
  'Alu automatically recognizes cards you have trouble learning, and tags them as "leeches"',
  'If you\'ve created a deck you think will help others, you can choose to make it public',
  'Is 20 new cards per day too much? Too little? You can change this value in the deck\'s settings.',
  'Deleted decks can never be recovered! Be careful!',
  'Alu estimates how easy or hard a card is using an "ease factor". This determines when you next see the card.',
  'Suspended cards are never shown to you when studying. Use this feature to temporarily disable cards.',
  'Give flashcards tags to organize them',
  'Want to study a specific set of cards? Use the "Custom Study" feature.',
  'When studying flashcards, use the spacebar to reveal the answer and the number keys (1-4) to select a choice',
  'You can share decks with others by changing the "Sharing Setting" value',
  'When creating cards, click the snowflake icon to "freeze" a field',
  'Flashcards have a full rich text editor - you should never have to pay money to make things bold',
  'When taking notes, we recommend you disable spell checking, and focus more on the content than spelling and grammar',
  'Turning off notifications when taking notes or attending class can help you focus and create better notes',
  'Use the "Flashcard Search" feature to find flashcards',
  'You can create a "filtered deck" out of flashcards with the "Flashcard Search" feature. This is useful if you are trying to study a specific topic you need extra help on.',
  'Images help you remember information better',
  'Remember to keep flashcards as simple as possible - no paragraph long explanations',
  'Cloze cards let you hide words or phrases in a sentence',
  '20 new flashcards every day for 2 months and you\'ll learn 1200 new items',
  'If you copy a shared deck, you will occasionally need to check for updates to automatically get all the new flashcards',
  '"Tasks" can help you remember to review subjects that are hard to make flashcards out of',
  'If you ever find a bug, please report it',
  'If you ever have a feature suggestion or improvement, please share it!',
  'Alu isn\'t just for school, you can use Alu to memorize anything related to your hobbies as well',
  'Don\'t forget to add tags to your cards!',
  'If you want to temporarily disable a flashcard, you can "Suspend" it',
  'Alu shows you flashcards right before you forget them',
  'The forgetting curve is the decline of memory retention over time, Alu attempts to model this to optimize when you should see flashcards',
  'Every time you review a flashcard, it gets a little easier to remember',
  'Cloze flashcards allow you to {{c1::hide}} a phrase in a flashcard',
  'Only turn information you truly understand into flashcards',
  'Learn before you memorize',
  'Start from the basics before going into complex subjects',
  'You can drag and drop images into the flashcard and note editors',
  'If you press "Add Notes" in autonote, without adding any notes, it will simply skip to the next section',
  'Always keep in mind the "20 Rules of Formulating Knowledge" when creating flashcards (found on the welcome page)',
  'Making flashcards personal to you will help you remember them better',
  'Make sure your flashcards are all connected - don\'t have random pieces of knowledge floating around',
  'You can drag image files directly from desktop into the note and flashcard editor',
  'Never memorize content you don\'t understand',
  'You can import flashcards from Quizlet, Anki, and other programs through the "Import Deck" feature',
  'Make sure you don\'t have flashcards that are too similar; that will make them hard too remember',
  'Try to avoid "lists" in flashcards.  It is usually better to separate those lists into multiple flashcards, or use cloze-deletion.',
  // Random stuff
  'Hermann Ebbinghaus discovered the forgetting curve, which Alu is based on, in the 1800s',
  'Dr. Piotr Wozniak developed one of the first digital SR apps in the 1990s. His work has made Alu possible.',
  // 'You got this!',
  // '42 (forty-two) is the natural number that follows 41 and precedes 43.',
  // 'Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.',
  // 'Some static you see on TV screens is residual radiation from the big-bang.',
];

export const randomTip = randomTips[Math.floor(Math.random()*randomTips.length)];