const randomTips = [
  // Actual relevant tips
  'Use "Tab" to cycle through fields when creating flashcards',
  'You can choose to share decks with friends only',
  'You can add friends in Alu, then choose to share your decks with them',
  'Enjoying Alu? Don\'t forget to tell your friends!',
  'Looking for a pre-made deck? Check out the "explore" tab.',
  // 'Looking for a specific pre-made deck? Use the "search" tab.',
  // 'Alu automatically recognizes cards you have trouble learning, and tags them as "leeches"',
  'If you\'ve created a deck you think will help others, you can choose to share it with others',
  'Alu estimates how easy or hard a card is using an "ease factor". This determines when you next see the card.',
  // 'Suspended cards are never shown to you when studying. Use this feature to temporarily disable cards.',
  // 'Give flashcards tags to organize them',
  'You can organize flashcards into main sections and sub sections to make them easier to find',
  // 'Want to study a specific set of cards? Use the "Custom Study" feature.',
  'When studying flashcards, use the spacebar to reveal the answer and the number keys (1-4) to select a choice',
  // 'When creating cards, click the snowflake icon to "freeze" a field',
  'Flashcards have a full rich text editor - you should never have to pay money to make things bold',
  // 'Use the "Flashcard Search" feature to find flashcards',
  // 'You can create a "filtered deck" out of flashcards with the "Flashcard Search" feature. This is useful if you are trying to study a specific topic you need extra help on.',
  'Images help you remember information better',
  'Simple flashcards are easy to remember.  You can add longer explanations at the bottom, but they shouldn\'t be your primary focus.',
  'Don\'t be afraid to split up a large flashcard into multiple smaller ones',
  'Cloze cards let you hide words or phrases in a sentence',
  '20 new flashcards every day for 2 months and you\'ll learn 1200 new items',
  'If you ever have a feature suggestion or improvement, please share it!',
  'Alu isn\'t just for school, you can use Alu to memorize anything related to your hobbies as well',
  // 'If you want to temporarily disable a flashcard, you can "Suspend" it',
  'Alu shows you flashcards right before you forget them',
  'The forgetting curve is the decline of memory retention over time. Alu attempts to model this to optimize when you should see flashcards.',
  'Every time you review a flashcard, it gets a little easier to remember',
  'Cloze flashcards allow you to {{c1::hide}} a phrase in a flashcard',
  'Only turn information you truly understand into flashcards',
  'Start from the basics before going into complex subjects',
  // 'You can drag and drop images into Alu\'s rich text editors',
  // 'You can drag image files directly from desktop into Alu\'s rich text editors',
  'Always keep in mind the "20 Rules of Formulating Knowledge" when creating flashcards (found on the welcome page)',
  'Making flashcards personal to you will help you remember them better',
  'Make sure your flashcards are all connected - don\'t have random pieces of knowledge floating around',
  'Never memorize content you don\'t understand',
  // 'You can import flashcards from Quizlet, Anki, and other programs through the "Import Deck" feature',
  'Make sure you don\'t have flashcards that are too similar; that will make them hard too remember',
  'Try to avoid "lists" in flashcards.  It is usually better to separate those lists into multiple flashcards, or use cloze-deletion.',
  'You can bookmark deck game settings for an easy way to play your favorite games',
  'It\'s much more efficient to have a big deck, and organize units with sections, than it is to have a bunch of small decks for each unit',
  'You can view advanced statistics about your deck through "Other > Statistics"',
  'Teachers can create classes of students, so that they can track their students\' progress',
  // 'Most people find doing Alu reviews in the morning (before school) more efficient and enjoyable',
  'Be honest with your Alu reviews, it\'s only designed to help you',
  // Random stuff
  'Hermann Ebbinghaus discovered the forgetting curve, which Alu is based on, in the 1800s',
  'Dr. Piotr Wozniak developed one of the first digital SR apps in the 1990s. His work has made Alu possible.',
  'The word "flashcard" appears over 3000 times in Alu\'s source code',
];

export const randomTip = randomTips[Math.floor(Math.random()*randomTips.length)];
